[versions]
freemarker = "2.3.30"
jackson = "2.11.1"
kotlin = "2.1.21"
kotlinx-cli = "0.3.4"
ktlint = "12.3.0"
shadow = "8.1.1"

[libraries]
freemarker = { module = "org.freemarker:freemarker", version.ref = "freemarker" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-dataformat-yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson" }
jackson-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinx-cli = { module = "org.jetbrains.kotlinx:kotlinx-cli", version.ref = "kotlinx-cli" }

[bundles]
jackson = [
    "jackson-databind",
    "jackson-dataformat-yaml",
    "jackson-kotlin",
]
kotlin = [
    "kotlin-stdlib-jdk8",
    "kotlinx-cli",
]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
